//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int CarId { get; set; }
        public string CarMake { get; set; }
        public string CarRegistrationNo { get; set; }
        public string CarFuelState { get; set; }
        public Nullable<int> CarKmOut { get; set; }
        public Nullable<int> CarKmIn { get; set; }
        public Nullable<int> TotalKm { get; set; }
        public Nullable<int> KmBill { get; set; }
        public string TimeOut { get; set; }
        public string TImeIn { get; set; }
        public Nullable<int> TimeBill { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public string DateOut { get; set; }
        public string DateIn { get; set; }
        public string CarOwner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
