//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalAgreement
    {
        public int RentalAgreementId { get; set; }
        public string AcutalItinerary { get; set; }
        public Nullable<int> ReservationId { get; set; }
        public Nullable<int> HPkr { get; set; }
        public Nullable<int> KPkr { get; set; }
        public Nullable<int> DPkr { get; set; }
        public Nullable<int> TollTaxCharges { get; set; }
        public Nullable<int> GST { get; set; }
        public Nullable<int> DriverCharges { get; set; }
        public Nullable<int> TotalCharges { get; set; }
        public string AgreementClosed { get; set; }
        public Nullable<int> AgreementFuel { get; set; }
        public Nullable<int> PrePayment { get; set; }
        public Nullable<int> AmountDue { get; set; }
        public Nullable<int> AgreementKmOut { get; set; }
        public Nullable<int> AgreementKmIn { get; set; }
        public Nullable<int> AgreementTotalKm { get; set; }
        public string AgreementTimeOut { get; set; }
        public string AgreementTimeIn { get; set; }
        public Nullable<int> AgreementTotalTime { get; set; }
        public string AgreementDateOut { get; set; }
        public string AgreementDateIn { get; set; }
        public string FuelOut { get; set; }
        public Nullable<int> DailyCharges { get; set; }
        public Nullable<int> MonthlyCharges { get; set; }
        public string FuelIn { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
