//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.RentalAgreements = new HashSet<RentalAgreement>();
        }
    
        public int ReservationId { get; set; }
        public string RentingStation { get; set; }
        public string MethodOfPayment { get; set; }
        public string BillingAddress { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> ReservationDateTime { get; set; }
        public Nullable<System.DateTime> BookedAt { get; set; }
        public Nullable<int> CarId { get; set; }
        public int ClientId { get; set; }
        public string Note { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string CheckInStation { get; set; }
        public Nullable<int> StaffId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalAgreement> RentalAgreements { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
